# Generated by Django 5.0.6 on 2024-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
