# Generated by Django 5.0.6 on 2024-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_is_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
