# Generated by Django 5.0.6 on 2024-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
