# Generated by Django 5.0.6 on 2024-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orderstatus_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='rgb',
            field=models.CharField(default=2, max_length=7),
            preserve_default=False,
        ),
    ]
