# Generated by Django 5.0.6 on 2024-07-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_headerimage_video_alter_headerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='size',
            name='chest_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='size',
            name='shoulder_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='size',
            name='top_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='size',
            name='waist_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
