# Generated by Django 5.0.6 on 2024-07-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_laundryservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='shoews_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='size',
            name='shoews_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
